0*true
1*true
2*true
#livio.pack.lang.en_US.DictionaryTextSelected*true
4*false
5*true
6*true
7*false
8*false
9*false
3*false
10*false
#com.duckduckgo.app.SelectedTextSearchActivity*true
#com.google.android.apps.translate.copydrop.CopyDropContextMenuActivity*true
#com.ichi2.anki.CardBrowserContextMenuAction*true
#com.mindtwisted.kanjistudy.activity.SearchActivity*true
#com.opera.android.PrivateSearch*true
